use agil_integration::websocket::error::WebSocketError;
use thiserror::Error;

/// Errors generated by Agil-Data
#[derive(Debug, Error)]
pub enum AgilDataError {
    #[error("Websocket error: {0}")]
    WebSocketError(#[from] WebSocketError),
    #[error("Websocket error")]
    WSERROR,
    #[error("Couldn't subscribe, validation timeout reached")]
    ValidationTimeout(std::time::Duration),
    #[error("Failed subscription response")]
    FailedSubscription,
    #[error("Message out of sequence")]
    OutOfSequenceMessage,
    #[error("Error validating a subscription")]
    SubscriptionValidation,
    #[error("Error parsing data")]
    ParseError,
}
